[UED-1160] [Add cookie consent dialog for milvus.io]
milvus-io/milvus.io pull request #995
Opened 2022-03-15 09:13 UTC by iynewz

2022-03-15 09:27 UTC, shanghaikid commented
Can you provide some screenshot?

2022-03-15 09:38 UTC, iynewz commented
> Can you provide some screenshot?

Sure, here are how the consent bar looks like on different screen sizes:
![image](https://user-images.githubusercontent.com/81401074/158348587-1f69771f-cbb0-4fb5-83ad-9dffbc12eec9.png)
![image](https://user-images.githubusercontent.com/81401074/158348886-106566c7-506a-42f3-afc8-0c32c935ed9c.png)
![image](https://user-images.githubusercontent.com/81401074/158349001-21be2825-47b0-4933-afaa-b37b89a0245a.png)
![image](https://user-images.githubusercontent.com/81401074/158349063-d600ebca-1731-4881-91fb-d42f3139e4d8.png)
![image](https://user-images.githubusercontent.com/81401074/158349170-76b43aa1-2614-4d05-b5fc-9ff114dffe39.png)

2022-03-15 09:49 UTC, nameczz requested changes

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +            <p className={styles.headerContent}>How we use cookies</p>
need i18n for the hard code text. Support cn and en.

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +              By continuing to browse or by clicking ‘Accept’, you agree to the
same here

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +function setValue(key, value) {
rename to setLocalStorage is more clear to me

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +function getValue(key, defaultValue) {
rename to getLocalStorage is more clear to me

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +    ? JSON.parse(window.localStorage.getItem(key))
JSON.parse will cause some error when param is not json, we may need to use try catch for JSON.parse

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +  }
should we need useEffect here

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +  const EnableAnalytics = () => {
The first letter of the normal function name should be lowercase. Only react function component or class is capital.

2022-03-15 09:49 UTC, nameczz commented on src/components/milvusCookieConsent/index.jsx
> +  const [value, setter] = React.useState(() => {
For useState, normally we use like [value,setValue] is more clear for us to know what value we set.

2022-03-16 09:03 UTC, nameczz approved these changes

2022-03-16 09:03 UTC, merged